In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D

In [2]:
dataset = pd.read_csv('data/SaratogaHouses.csv')

In [7]:
X = dataset[['livingArea','landValue','rooms','centralAir']].values
y = dataset['price'].values

In [8]:
pd.unique(dataset['centralAir'])

array(['No', 'Yes'], dtype=object)

In [9]:
X[:,-1]#-1 means last column

array(['No', 'No', 'No', ..., 'No', 'No', 'No'],
      shape=(1728,), dtype=object)

In [10]:
X

array([[906, 50000, 5, 'No'],
       [1953, 22300, 6, 'No'],
       [1944, 7300, 8, 'No'],
       ...,
       [1099, 20400, 3, 'No'],
       [1225, 16800, 7, 'No'],
       [1959, 26000, 6, 'No']], shape=(1728, 4), dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder#scikit learn - to convert text to numbers

In [12]:
encoder = LabelEncoder()
X[:,-1] = encoder.fit_transform(X[:,-1])#jo last column hai usko fit krdo encoder me

In [13]:
X[:,-1]

array([0, 0, 0, ..., 0, 0, 0], shape=(1728,), dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
fuel = dataset['fuel'].values

In [16]:
pd.unique(fuel)

array(['electric', 'gas', 'oil'], dtype=object)

In [17]:
fuel = encoder.fit_transform(fuel)

In [18]:
fuel[:20]

array([0, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2])

In [ ]:
fuel = fuel.reshape(-1,1)#horizontal to vertical
oneHot = OneHotEncoder()
fuel = oneHot.fit_transform(fuel)
#one hot encoding -sparse matrix

In [21]:
fuel

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1728 stored elements and shape (1728, 3)>

In [18]:
fuel.toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], shape=(1728, 3))

In [22]:
X

array([[906, 50000, 5, 0],
       [1953, 22300, 6, 0],
       [1944, 7300, 8, 0],
       ...,
       [1099, 20400, 3, 0],
       [1225, 16800, 7, 0],
       [1959, 26000, 6, 0]], shape=(1728, 4), dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler#data large - X scale -10L 20L ,Y Scale - 1,2,3 - ye 0to1 k bich

In [27]:
std = StandardScaler()
X = std.fit_transform(X)

X

array([[-1.36985441,  0.44108417, -0.88163155, -0.76221375],
       [ 0.31951971, -0.350095  , -0.44981202, -0.76221375],
       [ 0.30499787, -0.77853137,  0.41382706, -0.76221375],
       ...,
       [-1.05844161, -0.4043636 , -1.74527063, -0.76221375],
       [-0.85513584, -0.50718833, -0.01799248, -0.76221375],
       [ 0.32920094, -0.24441402, -0.44981202, -0.76221375]],
      shape=(1728, 4))

In [28]:
y = y.reshape(-1,1)
y = std.fit_transform(y)

In [29]:
y

array([[-0.80748259],
       [-0.31349249],
       [-1.04627242],
       ...,
       [-0.17341939],
       [-0.88369211],
       [-1.0229015 ]], shape=(1728, 1))

In [30]:
B = np.zeros(X.shape[1])

In [25]:
B

array([0., 0., 0., 0.])

In [26]:
X0 = np.ones(X.shape[0])

In [27]:
X[:,3]

array([-0.76221375, -0.76221375, -0.76221375, ..., -0.76221375,
       -0.76221375, -0.76221375], shape=(1728,))

In [28]:
X = np.array([X0, X[:,0],X[:,1],X[:,2],])

In [29]:
X[:10]

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-1.36985441,  0.31951971,  0.30499787, ..., -1.05844161,
        -0.85513584,  0.32920094],
       [ 0.44108417, -0.350095  , -0.77853137, ..., -0.4043636 ,
        -0.50718833, -0.24441402],
       [-0.88163155, -0.44981202,  0.41382706, ..., -1.74527063,
        -0.01799248, -0.44981202]], shape=(4, 1728))

In [30]:
X.shape

(4, 1728)

In [31]:
n = len(X)#how may rows
epochs = 5000 #kitne bar loop chalega
alpha = 0.001 #learning rate

In [32]:
X.shape

(4, 1728)

In [33]:
X = X.T

In [34]:
X.shape

(1728, 4)

In [35]:
X[:5]

array([[ 1.        , -1.36985441,  0.44108417, -0.88163155],
       [ 1.        ,  0.31951971, -0.350095  , -0.44981202],
       [ 1.        ,  0.30499787, -0.77853137,  0.41382706],
       [ 1.        ,  0.30499787, -0.45291972, -0.88163155],
       [ 1.        , -1.47634791, -0.5586007 , -1.74527063]])

In [36]:
def cost_function(X,y,B):
    return (np.sum((np.dot(X,B) - y) ** 2)) / (2 * n)

In [37]:
cost_function(X,y,B)

np.float64(373247.9999999999)

In [57]:
def gradient_descent(X,y,B,epochs,alpha):
    cost_history = [0] * epochs
    for i in range(epochs):
        y_pred = X.dot(B)
        loss = y_pred - y
        #gradient descent - minimising the loss
        gradient = X.T.dot(loss) / n
        B = B - alpha * gradient
        print("B =",B)
        cost_history[i] = cost_function(X,y,B)
#         print(i)
    return cost_history, B

In [58]:
cost,b = gradient_descent(X,y.flatten(),B,epochs=5000,alpha=0.0001)

B = [5.86197757e-18 3.07752581e-02 2.51106709e-02 2.29465493e-02]
B = [1.07913678e-17 5.90344082e-02 4.82773377e-02 4.36022022e-02]
B = [1.42996726e-17 8.49943156e-02 6.96595854e-02 6.21707708e-02]
B = [1.79412041e-17 1.08853098e-01 8.94035063e-02 7.88383289e-02]
B = [2.36255460e-17 1.30791745e-01 1.07642855e-01 9.37747462e-02]
B = [2.67341704e-17 1.50975597e-01 1.24500105e-01 1.07135091e-01]
B = [3.02202707e-17 1.69555694e-01 1.40087410e-01 1.19060911e-01]
B = [3.33955086e-17 1.86670018e-01 1.54507491e-01 1.29681404e-01]
B = [3.71480624e-17 2.02444611e-01 1.67854437e-01 1.39114487e-01]
B = [4.14113188e-17 2.16994615e-01 1.80214445e-01 1.47467773e-01]
B = [4.30544489e-17 2.30425210e-01 1.91666494e-01 1.54839464e-01]
B = [4.62518912e-17 2.42832474e-01 2.02282958e-01 1.61319166e-01]
B = [4.91606755e-17 2.54304171e-01 2.12130170e-01 1.66988637e-01]
B = [5.12256904e-17 2.64920469e-01 2.21268936e-01 1.71922461e-01]
B = [5.30686606e-17 2.74754596e-01 2.29755007e-01 1.76188676e-01]
B = [5.475

In [56]:
b

array([2.36699549e-17, 5.48036921e-01, 3.41088765e-01, 2.71546080e-02])

In [55]:
cost

[np.float64(195.85202215165236),
 np.float64(178.97984091107705),
 np.float64(164.84512619817485),
 np.float64(152.9982727406247),
 np.float64(143.06376283486009),
 np.float64(134.72794470864665),
 np.float64(127.72882778273471),
 np.float64(121.84756193949146),
 np.float64(116.90132285387043),
 np.float64(112.73737131965477),
 np.float64(109.22809280874371),
 np.float64(106.26685548334123),
 np.float64(103.76455158391676),
 np.float64(101.6467094111373),
 np.float64(99.85108173517045),
 np.float64(98.32563200829361),
 np.float64(97.0268527338018),
 np.float64(95.91836117925794),
 np.float64(94.96972666874325),
 np.float64(94.15549124214839),
 np.float64(93.45435177617816),
 np.float64(92.84847692741486),
 np.float64(92.32293665432569),
 np.float64(91.8652257459645),
 np.float64(91.46486585009426),
 np.float64(91.11307305254918),
 np.float64(90.8024801963688),
 np.float64(90.5269049132869),
 np.float64(90.28115582975784),
 np.float64(90.06087065345201),
 np.float64(89.8623808846319),
 

In [59]:
B.shape, X.shape, y.shape

((4,), (1728, 4), (1728, 1))

In [60]:
y_pred = X.dot(B)

In [61]:
y_pred.shape

(1728,)

In [62]:
loss = y_pred - y.flatten()

In [63]:
loss.shape

(1728,)

In [46]:
grad = X.T.dot(loss) / n

In [47]:
grad

array([-5.86197757e-14, -3.07752581e+02, -2.51106709e+02, -2.29465493e+02])